"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _hero_section from './hero-section.bones.json'
import _occasion_grid from './occasion-grid.bones.json'
import _gallery_story from './gallery-story.bones.json'
import _services_page from './services-page.bones.json'

registerBones({
  "hero-section": _hero_section,
  "occasion-grid": _occasion_grid,
  "gallery-story": _gallery_story,
  "services-page": _services_page,
})
