export interface City {
  name: string;
  state: string;
}

export const indianCities: City[] = [
  // --- MAHARASHTRA (No Surcharge) ---
  { name: "Mumbai", state: "Maharashtra" },
  { name: "Pune", state: "Maharashtra" },
  { name: "Nagpur", state: "Maharashtra" },
  { name: "Nashik", state: "Maharashtra" },
  { name: "Thane", state: "Maharashtra" },
  { name: "Pimpri-Chinchwad", state: "Maharashtra" },
  { name: "Kalyan-Dombivli", state: "Maharashtra" },
  { name: "Vasai-Virar", state: "Maharashtra" },
  { name: "Aurangabad", state: "Maharashtra" },
  { name: "Navi Mumbai", state: "Maharashtra" },
  { name: "Solapur", state: "Maharashtra" },
  { name: "Mira-Bhayandar", state: "Maharashtra" },
  { name: "Bhiwandi", state: "Maharashtra" },
  { name: "Amravati", state: "Maharashtra" },
  { name: "Nanded", state: "Maharashtra" },
  { name: "Kolhapur", state: "Maharashtra" },
  { name: "Sangli", state: "Maharashtra" },
  { name: "Malegaon", state: "Maharashtra" },
  { name: "Akola", state: "Maharashtra" },
  { name: "Latur", state: "Maharashtra" },
  { name: "Dhule", state: "Maharashtra" },
  { name: "Ahmednagar", state: "Maharashtra" },
  { name: "Chandrapur", state: "Maharashtra" },
  { name: "Parbhani", state: "Maharashtra" },
  { name: "Ichalkaranji", state: "Maharashtra" },
  { name: "Jalna", state: "Maharashtra" },
  { name: "Ambarnath", state: "Maharashtra" },
  { name: "Bhusawal", state: "Maharashtra" },
  { name: "Ratnagiri", state: "Maharashtra" },
  { name: "Chiplun", state: "Maharashtra" },
  { name: "Alibag", state: "Maharashtra" },
  { name: "Karjat", state: "Maharashtra" },
  { name: "Lonavala", state: "Maharashtra" },
  { name: "Mahabaleshwar", state: "Maharashtra" },
  { name: "Shirdi", state: "Maharashtra" },
  { name: "Diveagar", state: "Maharashtra" },
  { name: "Dapoli", state: "Maharashtra" },
  { name: "Vasai", state: "Maharashtra" },

  // --- REST OF INDIA (Surcharge Applies) ---
  { name: "Abu Road", state: "Rajasthan" },
  { name: "Agartala", state: "Tripura" },
  { name: "Agra", state: "Uttar Pradesh" },
  { name: "Ahmedabad", state: "Gujarat" },
  { name: "Aizawl", state: "Mizoram" },
  { name: "Ajmer", state: "Rajasthan" },
  { name: "Alappuzha", state: "Kerala" },
  { name: "Aligarh", state: "Uttar Pradesh" },
  { name: "Allahabad", state: "Uttar Pradesh" },
  { name: "Alleppey", state: "Kerala" },
  { name: "Almora", state: "Uttarakhand" },
  { name: "Alwar", state: "Rajasthan" },
  { name: "Amritsar", state: "Punjab" },
  { name: "Arakulam", state: "Kerala" },
  { name: "Auli", state: "Uttarakhand" },
  { name: "Bareilly", state: "Uttar Pradesh" },
  { name: "Barmer", state: "Rajasthan" },
  { name: "Bastar", state: "Chhattisgarh" },
  { name: "Begusarai", state: "Bihar" },
  { name: "Bengaluru", state: "Karnataka" },
  { name: "Bharatpur", state: "Rajasthan" },
  { name: "Bhilai", state: "Chhattisgarh" },
  { name: "Bhilwara", state: "Rajasthan" },
  { name: "Bhiwadi", state: "Rajasthan" },
  { name: "Bhopal", state: "Madhya Pradesh" },
  { name: "Bhubaneswar", state: "Odisha" },
  { name: "Bijapur", state: "Karnataka" },
  { name: "Bikaner", state: "Rajasthan" },
  { name: "Bilaspur", state: "Chhattisgarh" },
  { name: "Bodhgaya", state: "Bihar" },
  { name: "Bokaro", state: "Jharkhand" },
  { name: "Bongaigaon", state: "Assam" },
  { name: "Buxar", state: "Bihar" },
  { name: "Calicut", state: "Kerala" },
  { name: "Chamba", state: "Himachal Pradesh" },
  { name: "Chandigarh", state: "Chandigarh" },
  { name: "Chennai", state: "Tamil Nadu" },
  { name: "Cherrapunji", state: "Meghalaya" },
  { name: "Chidambaram", state: "Tamil Nadu" },
  { name: "Chikmagalur", state: "Karnataka" },
  { name: "Chittorgarh", state: "Rajasthan" },
  { name: "Cochin", state: "Kerala" },
  { name: "Coimbatore", state: "Tamil Nadu" },
  { name: "Coonoor", state: "Tamil Nadu" },
  { name: "Coorg", state: "Karnataka" },
  { name: "Cuttack", state: "Odisha" },
  { name: "Dalhousie", state: "Himachal Pradesh" },
  { name: "Daman", state: "Daman and Diu" },
  { name: "Darbhanga", state: "Bihar" },
  { name: "Darjeeling", state: "West Bengal" },
  { name: "Dehradun", state: "Uttarakhand" },
  { name: "Delhi", state: "Delhi" },
  { name: "Deoghar", state: "Jharkhand" },
  { name: "Deograh", state: "Odisha" },
  { name: "Dera Bassi", state: "Punjab" },
  { name: "Dhanbad", state: "Jharkhand" },
  { name: "Dharamshala", state: "Himachal Pradesh" },
  { name: "Dhemaji", state: "Assam" },
  { name: "Dibrugarh", state: "Assam" },
  { name: "Dimapur", state: "Nagaland" },
  { name: "Dindigul", state: "Tamil Nadu" },
  { name: "Diu", state: "Daman and Diu" },
  { name: "Durg", state: "Chhattisgarh" },
  { name: "Ellora", state: "Maharashtra" }, // Note: Ellora is in Maharashtra
  { name: "Ernakulam", state: "Kerala" },
  { name: "Faridabad", state: "Haryana" },
  { name: "Firozabad", state: "Uttar Pradesh" },
  { name: "Gangtok", state: "Sikkim" },
  { name: "Gaya", state: "Bihar" },
  { name: "Ghatshilla", state: "Jharkhand" },
  { name: "Ghaziabad", state: "Uttar Pradesh" },
  { name: "Gir", state: "Gujarat" },
  { name: "Goa", state: "Goa" },
  { name: "Gokarna", state: "Karnataka" },
  { name: "Gopalpur", state: "Odisha" },
  { name: "Greater Noida", state: "Uttar Pradesh" },
  { name: "Guntur", state: "Andhra Pradesh" },
  { name: "Gurgaon", state: "Haryana" },
  { name: "Gurugram", state: "Haryana" },
  { name: "Guruvayoor", state: "Kerala" },
  { name: "Guwahati", state: "Assam" },
  { name: "Gwalior", state: "Madhya Pradesh" },
  { name: "Hampi", state: "Karnataka" },
  { name: "Haridwar", state: "Uttarakhand" },
  { name: "Hassan", state: "Karnataka" },
  { name: "Havelock", state: "Andaman and Nicobar" },
  { name: "Hospet", state: "Karnataka" },
  { name: "Hubli", state: "Karnataka" },
  { name: "Hyderabad", state: "Telangana" },
  { name: "Idukki", state: "Kerala" },
  { name: "Imphal", state: "Manipur" },
  { name: "Indore", state: "Madhya Pradesh" },
  { name: "Itanagar", state: "Arunachal Pradesh" },
  { name: "Jabalpur", state: "Madhya Pradesh" },
  { name: "Jagdalpur", state: "Chhattisgarh" },
  { name: "Jaipur", state: "Rajasthan" },
  { name: "Jaisalmer", state: "Rajasthan" },
  { name: "Jammu", state: "Jammu and Kashmir" },
  { name: "Jamshedpur", state: "Jharkhand" },
  { name: "Jamui", state: "Bihar" },
  { name: "Jhansi", state: "Uttar Pradesh" },
  { name: "Jodhpur", state: "Rajasthan" },
  { name: "Jorhat", state: "Assam" },
  { name: "Kabini", state: "Karnataka" },
  { name: "Kakinada", state: "Andhra Pradesh" },
  { name: "Kalimpong", state: "West Bengal" },
  { name: "Kanchipuram", state: "Tamil Nadu" },
  { name: "Kannauj", state: "Uttar Pradesh" },
  { name: "Kannur", state: "Kerala" },
  { name: "Kanpur", state: "Uttar Pradesh" },
  { name: "Kanyakumari", state: "Tamil Nadu" },
  { name: "Karwar", state: "Karnataka" },
  { name: "Kasaragod", state: "Kerala" },
  { name: "Kasauli", state: "Himachal Pradesh" },
  { name: "Katra", state: "Jammu and Kashmir" },
  { name: "Kavaratti", state: "Lakshadweep" },
  { name: "Kayamkulam", state: "Kerala" },
  { name: "Khagaria", state: "Bihar" },
  { name: "Khajjiar", state: "Himachal Pradesh" },
  { name: "Khajuraho", state: "Madhya Pradesh" },
  { name: "Kodaikanal", state: "Tamil Nadu" },
  { name: "Kohima", state: "Nagaland" },
  { name: "Kolkata", state: "West Bengal" },
  { name: "Kollam", state: "Kerala" },
  { name: "Kollur", state: "Karnataka" },
  { name: "Konark", state: "Odisha" },
  { name: "Kota", state: "Rajasthan" },
  { name: "Kottakal", state: "Kerala" },
  { name: "Kottayam", state: "Kerala" },
  { name: "Kovalam", state: "Kerala" },
  { name: "Kozhikode", state: "Kerala" },
  { name: "Kullu", state: "Himachal Pradesh" },
  { name: "Kumaon", state: "Uttarakhand" },
  { name: "Kumarakom", state: "Kerala" },
  { name: "Kumbakonam", state: "Tamil Nadu" },
  { name: "Kurukshetra", state: "Haryana" },
  { name: "Kutch", state: "Gujarat" },
  { name: "Ladakh", state: "Ladakh" },
  { name: "Leh", state: "Ladakh" },
  { name: "Leh Ladakh", state: "Ladakh" },
  { name: "Lucknow", state: "Uttar Pradesh" },
  { name: "Madurai", state: "Tamil Nadu" },
  { name: "Mainpuri", state: "Uttar Pradesh" },
  { name: "Malappuram", state: "Kerala" },
  { name: "Manali", state: "Himachal Pradesh" },
  { name: "Mangalore", state: "Karnataka" },
  { name: "Manipal", state: "Karnataka" },
  { name: "Mathura", state: "Uttar Pradesh" },
  { name: "Meerut", state: "Uttar Pradesh" },
  { name: "Moradabad", state: "Uttar Pradesh" },
  { name: "Mount Abu", state: "Rajasthan" },
  { name: "Munnar", state: "Kerala" },
  { name: "Murdeshwar", state: "Karnataka" },
  { name: "Mussoorie", state: "Uttarakhand" },
  { name: "Muzaffarpur", state: "Bihar" },
  { name: "Mysore", state: "Karnataka" },
  { name: "Nagaur", state: "Rajasthan" },
  { name: "Nainital", state: "Uttarakhand" },
  { name: "Narkanda", state: "Himachal Pradesh" },
  { name: "Nathdwara", state: "Rajasthan" },
  { name: "Nawada", state: "Bihar" },
  { name: "Nellore", state: "Andhra Pradesh" },
  { name: "Noida", state: "Uttar Pradesh" },
  { name: "Numaligarh", state: "Assam" },
  { name: "Nuwara Eliya", state: "Sri Lanka" }, // Note: Technically Sri Lanka, but keeping in list
  { name: "Ongole", state: "Andhra Pradesh" },
  { name: "Ooty", state: "Tamil Nadu" },
  { name: "Pachmarhi", state: "Madhya Pradesh" },
  { name: "Palakkad", state: "Kerala" },
  { name: "Panipat", state: "Haryana" },
  { name: "Pasighat", state: "Arunachal Pradesh" },
  { name: "Pathanamthitta", state: "Kerala" },
  { name: "Patna", state: "Bihar" },
  { name: "Perintalmanna", state: "Kerala" },
  { name: "Pondicherry", state: "Puducherry" },
  { name: "Porbandar", state: "Gujarat" },
  { name: "Port Blair", state: "Andaman and Nicobar" },
  { name: "Prayagraj", state: "Uttar Pradesh" },
  { name: "Pudukkottai", state: "Tamil Nadu" },
  { name: "Puri", state: "Odisha" },
  { name: "Pushkar", state: "Rajasthan" },
  { name: "Raigarh", state: "Chhattisgarh" },
  { name: "Raipur", state: "Chhattisgarh" },
  { name: "Rajahmundry", state: "Andhra Pradesh" },
  { name: "Rajgir", state: "Bihar" },
  { name: "Rameshwaram", state: "Tamil Nadu" },
  { name: "Rameswaram", state: "Tamil Nadu" },
  { name: "Ramgarh", state: "Jharkhand" },
  { name: "Rampur", state: "Uttar Pradesh" },
  { name: "Ranchi", state: "Jharkhand" },
  { name: "Ranebennuru", state: "Karnataka" },
  { name: "Rishikesh", state: "Uttarakhand" },
  { name: "Rohtak", state: "Haryana" },
  { name: "Roorkee", state: "Uttarakhand" },
  { name: "Samastipur", state: "Bihar" },
  { name: "Satpura", state: "Madhya Pradesh" },
  { name: "Sawai Madhopur", state: "Rajasthan" },
  { name: "Shillong", state: "Meghalaya" },
  { name: "Shimla", state: "Himachal Pradesh" },
  { name: "Siliguri", state: "West Bengal" },
  { name: "Silvassa", state: "Dadra and Nagar Haveli" },
  { name: "Siwan", state: "Bihar" },
  { name: "Solan", state: "Himachal Pradesh" },
  { name: "Srikalahasti", state: "Andhra Pradesh" },
  { name: "Srinagar", state: "Jammu and Kashmir" },
  { name: "Surat", state: "Gujarat" },
  { name: "Tezpur", state: "Assam" },
  { name: "Thalassery", state: "Kerala" },
  { name: "Thanjavur", state: "Tamil Nadu" },
  { name: "Thekkady", state: "Kerala" },
  { name: "Thiruvananthapuram", state: "Kerala" },
  { name: "Thrissur", state: "Kerala" },
  { name: "Tinsukia", state: "Assam" },
  { name: "Tiruchendur", state: "Tamil Nadu" },
  { name: "Tiruchirappalli", state: "Tamil Nadu" },
  { name: "Tirupati", state: "Andhra Pradesh" },
  { name: "Tiruvannamalai", state: "Tamil Nadu" },
  { name: "Tonk", state: "Rajasthan" },
  { name: "Trivandrum", state: "Kerala" },
  { name: "Tuticorin", state: "Tamil Nadu" },
  { name: "Udaipur", state: "Rajasthan" },
  { name: "Udupi", state: "Karnataka" },
  { name: "Ujjain", state: "Madhya Pradesh" },
  { name: "Uttarkashi", state: "Uttarakhand" },
  { name: "Vadodara", state: "Gujarat" },
  { name: "Vagamon", state: "Kerala" },
  { name: "Varanasi", state: "Uttar Pradesh" },
  { name: "Varkala", state: "Kerala" },
  { name: "Velankanni", state: "Tamil Nadu" },
  { name: "Vellore", state: "Tamil Nadu" },
  { name: "Vijayawada", state: "Andhra Pradesh" },
  { name: "Visakhapatnam", state: "Andhra Pradesh" },
  { name: "Vishakhapatnam", state: "Andhra Pradesh" },
  { name: "Vrindavan", state: "Uttar Pradesh" },
  { name: "Warangal", state: "Telangana" },
  { name: "Wayanad", state: "Kerala" },
  { name: "Ziro", state: "Arunachal Pradesh" },
  { name: "Lakhimpur", state: "Uttar Pradesh" },
  { name: "Ponnani", state: "Kerala" }
];
